version: "3"

services: 
    web:
        container_name: springboot_mysqlv1
        # restart: always
        build: .
        ports:
            - "8090:8080"
        links:
          - mysql
        volumes:
          - .:/usr/src/app
    mysql:
        container_name: mysql57dbv1c
        image:  mysql:5.7
        restart: unless-stopped
        ports:
          - "3307:3306"  
        environment:
            MYSQL_ROOT_PASSWORD: root 
        volumes:
          - ./mysql_data:/var/lib/mysql     